language: objective-c
osx_image: xcode7.3

script:
  - xcodebuild -workspace OAuth1Tester.xcworkspace -scheme OAuth1Tester ONLY_ACTIVE_ARCH=NO
  - xcodebuild -workspace OAuth1Tester.xcworkspace -scheme OAuth1Tester -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' test