//
//  APIController.h
//  OAuth1Tester
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 08/03/2016
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "OAuthUtility.h"

@interface APIController : BaseController

/**
* Completion block definition for asynchronous call to OAuth1Test */
typedef void (^CompletedGetOAuth1Test)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* TODO: type endpoint description here
*/
- (void) getOAuth1TestWithCompletionBlock:(CompletedGetOAuth1Test) onCompleted;

@end