/*
 * OAuth1Tester
 *
 * This file was automatically generated by APIMATIC v2.0 on 08/03/2016
 */
#import <XCTest/XCTest.h>
#import "APIController.h"
#import "TestHelper.h"
#import "TestBaseController.h"

@interface  TestAPIController : TestBaseController
//Controller instance for all tests
@property APIController* controller;
@end 


@implementation  TestAPIController : TestBaseController

//Setup test class
//This method is called before the invocation of each test method in the test class
- (void)setUp {
    [super setUp];
    self.controller = [[APIController alloc]init];
}

//Teardown test class
//This method is called after the invocation of each test method in the test class
- (void)tearDown {
    [super tearDown];
}	


// Todo Add description for test testOAuth1Test    
-(void) testOAuth1Test {
    //Set up test expectations
    XCTestExpectation *expectation =[self expectationWithDescription:@"High Expectations"];

    // Set callback and perform API call
    [self.controller getOAuth1TestWithCompletionBlock:  ^(BOOL success, HttpContext* context, NSString* response, NSError* error) { 
       // Test response code
        XCTAssertEqual(200, context.response.statusCode);

        // Test whether the captured response is not null
        XCTAssertTrue(response!=nil);
		// Test whether the captured response is as we expected
	NSString* rawBody = [[NSString alloc] initWithData:context.response.rawBody encoding:NSUTF8StringEncoding];
        XCTAssertEqualObjects(
                @"You've passed the test!", 
                rawBody);
        [expectation fulfill];
    }];
    [self wait];
}



@end
