//
//  Configuration.h
//  OAuth1Tester
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 08/03/2016
//
#ifndef OAuth1Tester_Configuration_h
#define OAuth1Tester_Configuration_h

/** The base Uri for API calls */
extern NSString* Configuration_BaseUri;

/** The OAuth token to be set before API calls */
/** extern reference to the config variable OAuthToken */
extern NSString* Configuration_OAuthToken;

/** The OAuth token secret to be set before API calls */
/** extern reference to the config variable OAuthTokenSecret */
extern NSString* Configuration_OAuthTokenSecret;

/** The OAuth client id to be set before API calls */
/** extern reference to the config variable OAuthClientId */
extern NSString* Configuration_OAuthClientId;

/** The OAuth client secret to be set before API calls */
/** extern reference to the config variable OAuthClientSecret */
extern NSString* Configuration_OAuthClientSecret;

#endif
