//
//  Configuration.m
//  OAuth1Tester
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 08/03/2016
//
#import "Configuration.h"

/** The base Uri for API calls */
NSString* Configuration_BaseUri = @"http://www.testwronguri.com";

/** The OAuth token to be set before API calls */
/** Replace the value of OAuthToken with an appropriate value */
NSString* Configuration_OAuthToken = @"TODO: Replace";

/** The OAuth token secret to be set before API calls */
/** Replace the value of OAuthTokenSecret with an appropriate value */
NSString* Configuration_OAuthTokenSecret = @"TODO: Replace";

/** The OAuth client id to be set before API calls */
/** Replace the value of OAuthClientId with an appropriate value */
NSString* Configuration_OAuthClientId = @"TODO: Replace";

/** The OAuth client secret to be set before API calls */
/** Replace the value of OAuthClientSecret with an appropriate value */
NSString* Configuration_OAuthClientSecret = @"TODO: Replace";

