//
//  OAuthUtility.h
//  OAuth1Tester
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 08/03/2016
//
#import <Foundation/Foundation.h>
#include <CommonCrypto/CommonDigest.h>
#include <CommonCrypto/CommonHMAC.h>
#include <stdlib.h>
#import "APIHelper.h"
#import "Configuration.h"
#import "HttpRequest.h"
#import "Base64.h"

@interface OAuthUtility : NSObject

/**
* Appends the necessary OAuth credentials for making this authorized call
* @param	request	The out going request to access the resource
*/
+(void) appendOAuthParams:(HttpRequest*) request;

@end